# Generated by Django 4.2 on 2026-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners/'),
        ),
        migrations.AddField(
            model_name='store',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='stores/profiles/'),
        ),
    ]
