# Generated by Django 6.0.3 on 2026-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash / e-Wallet'), ('BANK', 'Online Banking'), ('CARD', 'Credit / Debit Card')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('to_pay', 'To Pay'), ('paid', 'Paid'), ('shipping', 'Shipping'), ('to_receive', 'To Receive'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('return_refund', 'Return/Refund')], default='to_pay', max_length=20),
        ),
    ]
