# Generated by Django 4.2 on 2026-03-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_store_banner_image_store_profile_picture'),
        ('api', '0003_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
    ]
