# Generated by Django 4.2 on 2026-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Is a Shop Owner?'),
        ),
    ]
